"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.initialize = exports.useEventTracker = exports.useConversionTracker = exports.getMetaConfigFromExpo = exports.Validator = exports.Crypto = exports.Logger = exports.NetworkService = exports.ATTService = exports.StorageService = exports.MetaEventMapper = exports.MetaProvider = exports.BaseProvider = exports.User = exports.DEFAULT_CONFIG = exports.EventPriority = exports.EventType = exports.EventBuilder = exports.BatchProcessor = exports.EventQueue = exports.ConversionTracker = void 0;
const ConversionTracker_1 = require("./core/ConversionTracker");
var ConversionTracker_2 = require("./core/ConversionTracker");
Object.defineProperty(exports, "ConversionTracker", { enumerable: true, get: function () { return ConversionTracker_2.ConversionTracker; } });
var EventQueue_1 = require("./core/EventQueue");
Object.defineProperty(exports, "EventQueue", { enumerable: true, get: function () { return EventQueue_1.EventQueue; } });
var BatchProcessor_1 = require("./core/BatchProcessor");
Object.defineProperty(exports, "BatchProcessor", { enumerable: true, get: function () { return BatchProcessor_1.BatchProcessor; } });
var Event_1 = require("./models/Event");
Object.defineProperty(exports, "EventBuilder", { enumerable: true, get: function () { return Event_1.EventBuilder; } });
Object.defineProperty(exports, "EventType", { enumerable: true, get: function () { return Event_1.EventType; } });
Object.defineProperty(exports, "EventPriority", { enumerable: true, get: function () { return Event_1.EventPriority; } });
var Config_1 = require("./models/Config");
Object.defineProperty(exports, "DEFAULT_CONFIG", { enumerable: true, get: function () { return Config_1.DEFAULT_CONFIG; } });
var User_1 = require("./models/User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_1.User; } });
var BaseProvider_1 = require("./providers/base/BaseProvider");
Object.defineProperty(exports, "BaseProvider", { enumerable: true, get: function () { return BaseProvider_1.BaseProvider; } });
var MetaProvider_1 = require("./providers/meta/MetaProvider");
Object.defineProperty(exports, "MetaProvider", { enumerable: true, get: function () { return MetaProvider_1.MetaProvider; } });
var MetaEventMapper_1 = require("./providers/meta/MetaEventMapper");
Object.defineProperty(exports, "MetaEventMapper", { enumerable: true, get: function () { return MetaEventMapper_1.MetaEventMapper; } });
var StorageService_1 = require("./services/StorageService");
Object.defineProperty(exports, "StorageService", { enumerable: true, get: function () { return StorageService_1.StorageService; } });
var ATTService_1 = require("./services/ATTService");
Object.defineProperty(exports, "ATTService", { enumerable: true, get: function () { return ATTService_1.ATTService; } });
var NetworkService_1 = require("./services/NetworkService");
Object.defineProperty(exports, "NetworkService", { enumerable: true, get: function () { return NetworkService_1.NetworkService; } });
var Logger_1 = require("./utils/Logger");
Object.defineProperty(exports, "Logger", { enumerable: true, get: function () { return Logger_1.Logger; } });
var Crypto_1 = require("./utils/Crypto");
Object.defineProperty(exports, "Crypto", { enumerable: true, get: function () { return Crypto_1.Crypto; } });
var Validator_1 = require("./utils/Validator");
Object.defineProperty(exports, "Validator", { enumerable: true, get: function () { return Validator_1.Validator; } });
var ExpoConfigHelper_1 = require("./utils/ExpoConfigHelper");
Object.defineProperty(exports, "getMetaConfigFromExpo", { enumerable: true, get: function () { return ExpoConfigHelper_1.getMetaConfigFromExpo; } });
var useConversionTracker_1 = require("./hooks/useConversionTracker");
Object.defineProperty(exports, "useConversionTracker", { enumerable: true, get: function () { return useConversionTracker_1.useConversionTracker; } });
var useEventTracker_1 = require("./hooks/useEventTracker");
Object.defineProperty(exports, "useEventTracker", { enumerable: true, get: function () { return useEventTracker_1.useEventTracker; } });
const initialize = async (config) => {
    const tracker = ConversionTracker_1.ConversionTracker.getInstance(config);
    await tracker.initialize();
    return tracker;
};
exports.initialize = initialize;
